filename="REPORT_OUTPUT/COIN/PRODUCTION/replay_coin_production_29016_-1.report"
echo "BCM2 with 1uA cut (mC)"
grep -oP '(?<=SHMS BCM2  Beam Cut Charge: )[0-9.]+' "$filename"
echo "Number of events:"
grep -oP '(?<=Accepted HMS Triggers         : )[0-9.]+' "$filename"
echo "pi+ track efficiency:"
grep -oP '(?<=HADRON SING FID TRACK EFFIC    :   )[0-9.]+' "$filename"
echo "e- track efficiency:"
grep -oP '(?<=E SING FID TRACK EFFIC         :   )[0-9.]+' "$filename"
echo "3/4 efficiency (SHMS 1st, HMS 2nd):"
grep -oP '(?<=3_of_4 EFF : )[0-9.]+' "$filename"
echo "HMS Cer eff:"
grep -oP '(?<=Overall HGC Efficiency: )[0-9.]+' "$filename"
echo "SHMS Cer eff:"
grep -oP '(?<=Overall HGC Efficiency:       )[0-9.]+' "$filename"

